mod.id = "quick_access"
mod.name = "Quick Access"
mod.group = "net.ray"
mod.version = "1.0.0"
mod.channel_tag = ""
mod.description = "Easily access crafting tables, enderchests, shulkers, etc... just by right clicking in your inventory."
mod.authors = ["ray"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "github.com"
mod.homepage_url = "github.com"
mod.issues_url = "github.com/issues"
mod.discord_url = ""
[[mod.pom.developers]]
id = "ray"
name = "ray"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."1.19.2"]
deps.minecraft = "1.19.2"
deps.fabric-api = "0.77.0+1.19.2"
deps.modmenu = "4.2.0-beta.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "15.0.0"

[fabric."1.21.7"]
deps.minecraft = "1.21.7"
deps.fabric-api = "0.128.1+1.21.7"
deps.modmenu = "15.0.0"
publish.additionalVersions = ["1.21.6"]

[fabric."26.1"]
deps.minecraft = "26.1"
deps.fabric-api = "0.145.1+26.1"
deps.modmenu = "18.0.0-alpha.8"
publish.additionalVersions = ["26.1.1", "26.1.2"]

[forge]

[forge."1.19.2"]
deps.minecraft = "1.19.2"
deps.forge = "43.5.2"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"

[neoforge."1.21.7"]
deps.minecraft = "1.21.7"
deps.neoforge = "21.7.1-beta"
publish.additionalVersions = ["1.21.6"]

[neoforge."26.1"]
deps.minecraft = "26.1"
deps.neoforge = "26.1.0.19-beta"
publish.additionalVersions = ["26.1.1", "26.1.2"]
